[package]
name = "smartconsole"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
pamsm = { version = "0", features = ["libpam"] }
base64 = { workspace = true }
crypto_box = { workspace = true }
qrcode = { workspace = true }
rand = { workspace = true }
